name: Maroc ip
favicon: null
layout_spectrum: 0.8880956298671663
typography_spectrum: 0.20253677084110677
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.07661896711215377
  lightness: 0.031039348570629954
  saturation: 0.149090661900118
  rhythmicContrast: 0.1176912272349
purpose: []
